#spring:
#  security:
#    oauth2:
#      resource server:
#        jwt:
#          jwk-set-uri: https://www.googleapis.com/service_accounts/v1/jwk/securetoken@system.gserviceaccount.com
#          issuer-uri: https://securetoken.google.com/movimentaif
#          audiences: movimentaif


spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          # Substitua 'movimentaif' pelo ID real do seu projeto Firebase
          issuer-uri: https://securetoken.google.com/movimentaif
          # O Spring ir√° deduzir o jwk-set-uri com base no issuer-uri.